config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  root 'home#index'
  resources :notifications, only: [:create, :new]

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable#, :validatable
end

app/models/notification.rb
class Notification < ActiveRecord::Base

  after_create :notify

  validates :sender_name, :message,
            presence: true

  validates :sender_email,
            presence: true,
            format: {with: /@/ }

  def mailer
    NotificationMailer
  end
  def notify
    mailer.visitor_email(self).deliver
    mailer.admin_email(self).deliver
  end
end

app/models/olala/label.rb
require_dependency Olala::Engine.root.join('app', 'models', 'olala', File.basename(__FILE__)).to_s

module Olala
  class Label
    def self.find_or_create_by_label label
      self.where(label: label).first || create(label: label)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # include Olala::CustomAuth

  def admin_namespace?
    request.subdomain.match(/\Aadmin\Z/) != nil
  end

  def main_domain_root_url
    root_url host: Rails.configuration.action_mailer.default_url_options[:host]
  end
  helper_method :admin_namespace?, :main_domain_root_url

  def after_sign_out_path_for resource_name_or_scope
    main_domain_root_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_admin!, if: proc{ admin_namespace? and not admin_signed_in? }

  def index
  end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def create
    @notification = Notification.create notification_params
    if @notification.save
      @notification = Notification.new
      flash.now[:notice] = "Votre message a bien été délivré a nos équipes commerciales."
    end
    render partial: "form"
  end

  def notification_params
    params.require(:notification).permit(:sender_email, :sender_name, :message)
  end
end

app/controllers/olala/labels_controller.rb
module Olala
  class LabelsController < ApplicationController

    before_filter :check_admin_right
    protect_from_forgery :except => :create

    def check_admin_right
      unless admin_signed_in?
        raise 'Access denied'
      end
    end

    def create
      params.permit(:label, :content)
      label = Label.find_or_create_by_label params[:label]
      label.content = params[:content] if params[:content]
      label.save

      expire_fragment 'home'
      render text: 'ok'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def devise_flash_messages
    k, v = {:notice =>:success, :alert => :error}.detect { |k,v| not flash[k].blank? }.to_a
    if k
      content_tag :div, class: "alert alert-#{v}" do
        flash[k].html_safe
      end
    end
  end

  def error_messages_for resource
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
      <div class="alert alert-error" >
        <ul class="unstyled" style="margin-bottom: 0">#{messages}</ul>
      </div>
    HTML
    resource.errors.blank? ? "" : html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
  <!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
  <!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
  <!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Connect-it</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    <!-- favicon.ico and apple-touch-icon.png -->
    <link rel="shortcut icon" href="<%= path_to_image('favicon.ico')%>">
    <!--<link rel="apple-touch-icon" href="<%= path_to_image('apple-touch-icon-57x57-precomposed.png')%>">-->
    <!--<link rel="apple-touch-icon" sizes="72x72" href="<%= path_to_image('apple-touch-icon-72x72-precomposed.png')%>">-->
    <!--<link rel="apple-touch-icon" sizes="114x114" href="<%= path_to_image('apple-touch-icon-114x114-precomposed.png')%>">-->

    <%= stylesheet_link_tag :application %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300' rel='stylesheet' type='text/css'>

    <!--<script src="js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>-->

    <!--&lt;!&ndash;<script type="text/javascript">&ndash;&gt;-->

<!--//      var _gaq = _gaq || [];-->
<!--//      _gaq.push(['_setAccount', 'UA-43482875-1']);-->
<!--//      _gaq.push(['_trackPageview']);-->
<!--//-->
<!--//      (function() {-->
<!--//        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;-->
<!--//        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';-->
<!--//        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);-->
<!--//      })();-->
<!--//-->
    <!--&lt;!&ndash;</script>&ndash;&gt;-->
  </head>
  <body data-spy="scroll" data-target=".navbar" class="<%= admin_signed_in? ? 'admin' : '' %>">

    <% if admin_namespace? and admin_signed_in? %>
      <div class="navbar navbar-fixed-top navbar-inverse" style="position:fixed">
        <div class="navbar-inner">
          <a class="brand" href="#">Admin mode</a>
          <ul class="nav" style="padding-top:0; float: right">
            <li class="active">
              <%= link_to "Log out", destroy_admin_session_path, method: :delete %>
            </li>
          </ul>
        </div>
      </div>
    <% end %>

    <%= cache "home", skip_digest: true do %>
      <section id="home">
        <div class="container">
          <div class="containerblack">
            <ul class="homenav left">
              <li><a href="#about" class="scrollto"><%= editable("About", "About")%></a></li>
            </ul>
            <ul class="homenav right">
              <li><a href="#contact" class="scrollto"><%= editable("Contact", "Contact")%></a></li>
            </ul>
            <h1><img src="<%= image_path("LOGO_170x150_YELLOW.png")%>"></h1>
            <div id="slider">
              <div class="slide"><%= editable "lead 1", "We make <strong>the finest design</strong> just for you."%></div>
              <div class="slide"><%= editable "lead 2", "We build <strong>strong brands</strong> to get ahead." %></div>
              <div class="slide"><%= editable "lead 3", "We aim to <strong>bigger sales</strong> and beyond."%></div>
            </div><!-- end: #slider -->
          </div>
          <a href="#contact" id="arrow_down"><%= editable "contact us", "See our work" %></a>
          <!--<a href="#contact" id="arrow_down"><%#= editable "contact us", "See our work" %></a>-->
        </div><!-- end: .containter -->
      </section><!-- end: #home -->

      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <a class="brand" href="#">CONNECTIC-IT</a>
            <div class="pull-right">
              <ul class="nav">
                <li><a href="#home"><%= editable "Home", "Home" %></a></li>
                <li><a href="#about"><%= editable "About", "About"%></a></li>
                <li><a href="#contact"><%= editable "Contact", "Contact"%></a></li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </div>
      </div>

      <section id="about">
        <div class="container">
          <h2 class="text-center"><%= editable "About", "About" %><i class="icon-about"><img src="<%=image_path("icon-about.png")%>"></i></h2>
          <div class="text-center lead marginer">
            <%= editable "lead About", "Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit."%>
          </div>
          <div class="text-center lead twocolumns1"><%= editable "about 1", "<strong>Lorem ipsum dolor</strong> sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam." %></div>
          <div class="text-center lead twocolumns2"><%= editable "about 2", "<strong>Lorem ipsum</strong> dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam." %></div>
          <div class="clear"></div>
        </div><!-- end: .container -->
      </section>
      <div class="container txtblock nrtwo">
        <div class="lead">
          <%= editable "transition 1",  "Our team is devoted to your happiness. Integer nec odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit diozo burit burizon."%>
          <a href="#contact" class="scrollto"><%= editable "Let`s talk.", "Let`s talk." %></a>
        </div>
      </div> <!-- end: container txtblock -->

      <section id="contact">
        <div class="container">
          <h2 class="text-center">
            <%= editable "Contact", "Contact" %>
            <i class="icon-contact"><img src="<%=image_path("icon-contact.png")%>"></i>
          </h2>
          <div class="text-center lead">
            <%= editable "lead Contact", "Let`s get together and create something beautiful for you and your business. The time is now. <strong>Go for it</strong>." %>
          </div>

          <div class="row">
            <div class="span7">
              <%= render partial: "notifications/form" %>
            </div>

            <div class="span3">
              <h3><%= editable "Meet us here", "Meet us here" %></h3>
              <address>
                <%= editable "address",
                "Beautiful street 55<br>
                Somewhere in Trencin<br>
                Slovakia" %>
              </address>

              <h3><%= editable "Ask a question", "Ask a question" %></h3>
              <p><a href="#"><%= editable "contact email", "hi@kozdo.com"%></a></p>

              <!--<h3>Apply for job</h3>-->
              <!--<p><a href="#">employme@kozdo.com</a></p>-->
            </div>
          </div><!-- end: .row -->
        </div><!-- end: .container -->
      </section><!-- end: #contact -->

      <footer>
        <a href="#home" class="scrollto">
          <img src="<%= image_path("LOGO_FOOTER_90x79_WHITE.png")%>">
        </a>
      </footer>
    <% end %>

    <% if admin_signed_in? %>
      <%= stylesheet_link_tag asset_path "aloha/css/aloha.css" %>
      <%= javascript_include_tag :admin %>
    <% else %>
      <%= javascript_include_tag :application %>
    <% end %>

    <% if admin_namespace? and not admin_signed_in? %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/layouts/email.html.haml
!!! XML
!!!
%html
  %head
    %title= t('.title')
    = stylesheet_link_tag "emails"
  %body
    .content
      -#= image_tag(attachments['logo.png'].url, id: "logo")
      = yield

app/views/notifications/_form.html.erb
<%= form_for @notification || Notification.new, url: notifications_path, remote: true, html: {id: "new_notification", class: "htmlform" } do |form| %>
  <%= devise_flash_messages %>
  <%= error_messages_for form.object %>
  <%= form.text_field :sender_name, placeholder: "Votre nom", required: true, autocomplete: 'OFF' %>
  <%= form.email_field :sender_email, placeholder: "E-mail", required: true, autocomplete: 'OFF' %>
  <%= form.text_area :message, cols: "1", rows: "5", placeholder: "Message", required: true, autocomplete: 'OFF' %>
  <button name="send" type="submit" class="btn"><%= editable "Send", "Envoyer" %></button>
  <div class="fade loader">
    <div class="progress progress-striped active">
      <div class="bar" style="width: 0;"></div>
    </div>
  </div>
<% end %>